export const vina = [
    {
        id: '1',
        naziv: 'Cabernet Sauvignon',
        tip_id: '1',
        regija: 'Bordeaux',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'crno voće, ribiz, šljiva, cedar, duhan',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '2',
        naziv: 'Sangiovese',
        tip_id: '1',
        regija: 'Toscana',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'crveno voće, trešnja, začini, zemljano',
        tijelo_id: '2',
        alkohol_min: 13,
        alkohol_max: 14
    },
    {
        id: '3',
        naziv: 'Merlot',
        tip_id: '1',
        regija: 'Bordeaux',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'šljiva, čokolada, biljno',
        tijelo_id: '2',
        alkohol_min: 13,
        alkohol_max: 14
    },
    {
        id: '4',
        naziv: 'Pinot Noir',
        tip_id: '1',
        regija: 'Burgundy',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '1',
        arome: 'jagoda, trešnja, zemljano',
        tijelo_id: '1',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '5',
        naziv: 'Syrah',
        tip_id: '1',
        regija: 'Rhone',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'crno voće, papar, dim',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '6',
        naziv: 'Malbec',
        tip_id: '1',
        regija: 'Mendoza',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'šljiva, čokolada, dim',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '7',
        naziv: 'Zinfandel',
        tip_id: '1',
        regija: 'California',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '2',
        arome: 'kupina, papar, džemasto',
        tijelo_id: '3',
        alkohol_min: 14,
        alkohol_max: 16
    },
    {
        id: '8',
        naziv: 'Tempranillo',
        tip_id: '1',
        regija: 'Rioja',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'trešnja, duhan, vanilija',
        tijelo_id: '2',
        alkohol_min: 13,
        alkohol_max: 14.5
    },
    {
        id: '9',
        naziv: 'Grenache',
        tip_id: '1',
        regija: 'Priorat',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'malina, začini',
        tijelo_id: '2',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '10',
        naziv: 'Nebbiolo',
        tip_id: '1',
        regija: 'Piedmont',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'ruža, katran, trešnja',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '11',
        naziv: 'Barbera',
        tip_id: '1',
        regija: 'Piedmont',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'trešnja, začini',
        tijelo_id: '2',
        alkohol_min: 12.5,
        alkohol_max: 14
    },
    {
        id: '12',
        naziv: 'Chianti',
        tip_id: '1',
        regija: 'Toscana',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'trešnja, biljno',
        tijelo_id: '2',
        alkohol_min: 12.5,
        alkohol_max: 13.5
    },
    {
        id: '13',
        naziv: 'Riesling',
        tip_id: '2',
        regija: 'Mosel',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '4',
        arome: 'citrusi, jabuka, cvjetno',
        tijelo_id: '1',
        alkohol_min: 8,
        alkohol_max: 12
    },
    {
        id: '14',
        naziv: 'Chardonnay',
        tip_id: '2',
        regija: 'Burgundy',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'jabuka, maslac, vanilija',
        tijelo_id: '3',
        alkohol_min: 13,
        alkohol_max: 14.5
    },
    {
        id: '15',
        naziv: 'Sauvignon Blanc',
        tip_id: '2',
        regija: 'Loire',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'citrusi, trava',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 13
    },
    {
        id: '16',
        naziv: 'Pinot Grigio',
        tip_id: '2',
        regija: 'Veneto',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'kruška, limun',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 12.5
    },
    {
        id: '17',
        naziv: 'Gewurztraminer',
        tip_id: '2',
        regija: 'Alsace',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '3',
        arome: 'lišće ruže, liči',
        tijelo_id: '2',
        alkohol_min: 13,
        alkohol_max: 14
    },
    {
        id: '18',
        naziv: 'Viognier',
        tip_id: '2',
        regija: 'Rhone',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'breskva, cvjetno',
        tijelo_id: '2',
        alkohol_min: 13,
        alkohol_max: 14
    },
    {
        id: '19',
        naziv: 'Albarino',
        tip_id: '2',
        regija: 'Galicia',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'citrusi, more',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 13
    },
    {
        id: '20',
        naziv: 'Moscato',
        tip_id: '2',
        regija: 'Piedmont',
        temperatura_min: 6,
        temperatura_max: 8,
        slatkoca_id: '4',
        arome: 'grožđe, cvjetno',
        tijelo_id: '1',
        alkohol_min: 5,
        alkohol_max: 8
    },
    {
        id: '21',
        naziv: 'Prosecco',
        tip_id: '3',
        regija: 'Veneto',
        temperatura_min: 6,
        temperatura_max: 8,
        slatkoca_id: '1',
        arome: 'jabuka, kruška, cvjetno',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 11.5
    },
    {
        id: '22',
        naziv: 'Champagne',
        tip_id: '3',
        regija: 'Champagne',
        temperatura_min: 6,
        temperatura_max: 8,
        slatkoca_id: '1',
        arome: 'citrusi, tost, kvasac',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 12.5
    },
    {
        id: '23',
        naziv: 'Cava',
        tip_id: '3',
        regija: 'Catalonia',
        temperatura_min: 6,
        temperatura_max: 8,
        slatkoca_id: '1',
        arome: 'citrusi, badem',
        tijelo_id: '2',
        alkohol_min: 11.5,
        alkohol_max: 12.5
    },
    {
        id: '24',
        naziv: 'Shiraz',
        tip_id: '1',
        regija: 'Barossa Valley',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'kupina, papar, čokolada',
        tijelo_id: '3',
        alkohol_min: 14,
        alkohol_max: 15.5
    },
    {
        id: '25',
        naziv: 'Petite Sirah',
        tip_id: '1',
        regija: 'California',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'borovnica, papar, tamno voće',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '26',
        naziv: 'Carmenere',
        tip_id: '1',
        regija: 'Central Valley',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'paprika, šljiva, začini',
        tijelo_id: '2',
        alkohol_min: 13,
        alkohol_max: 14.5
    },
    {
        id: '27',
        naziv: 'Primitivo',
        tip_id: '1',
        regija: 'Puglia',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '2',
        arome: 'šljiva, džem, začini',
        tijelo_id: '3',
        alkohol_min: 14,
        alkohol_max: 16
    },
    {
        id: '28',
        naziv: 'Montepulciano',
        tip_id: '1',
        regija: 'Abruzzo',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'trešnja, začini',
        tijelo_id: '2',
        alkohol_min: 12.5,
        alkohol_max: 14
    },
    {
        id: '29',
        naziv: 'Soave',
        tip_id: '2',
        regija: 'Veneto',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'jabuka, cvjetno',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 12.5
    },
    {
        id: '30',
        naziv: 'Greco di Tufo',
        tip_id: '2',
        regija: 'Campania',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'kruška, mineralno',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '31',
        naziv: 'Chenin Blanc',
        tip_id: '2',
        regija: 'Loire',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '3',
        arome: 'jabuka, med, cvjetno',
        tijelo_id: '2',
        alkohol_min: 11,
        alkohol_max: 13.5
    },
    {
        id: '32',
        naziv: 'Semillon',
        tip_id: '2',
        regija: 'Bordeaux',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'limun, vosak, med',
        tijelo_id: '2',
        alkohol_min: 11.5,
        alkohol_max: 13.5
    },
    {
        id: '33',
        naziv: 'Tokaji',
        tip_id: '2',
        regija: 'Tokaj',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '4',
        arome: 'med, marelica, cvjetno',
        tijelo_id: '3',
        alkohol_min: 11,
        alkohol_max: 13
    },
    {
        id: '34',
        naziv: 'Porto',
        tip_id: '4',
        regija: 'Douro',
        temperatura_min: 12,
        temperatura_max: 16,
        slatkoca_id: '4',
        arome: 'sušeno voće, čokolada',
        tijelo_id: '3',
        alkohol_min: 19,
        alkohol_max: 22
    },
    {
        id: '35',
        naziv: 'Sherry',
        tip_id: '4',
        regija: 'Jerez',
        temperatura_min: 8,
        temperatura_max: 14,
        slatkoca_id: '1',
        arome: 'orah, sol, oksidativno',
        tijelo_id: '2',
        alkohol_min: 15,
        alkohol_max: 20
    },
    {
        id: '36',
        naziv: 'Madeira',
        tip_id: '4',
        regija: 'Madeira',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '4',
        arome: 'karamela, orašasto',
        tijelo_id: '3',
        alkohol_min: 17,
        alkohol_max: 20
    },
    {
        id: '37',
        naziv: 'Gruner Veltliner',
        tip_id: '2',
        regija: 'Wachau',
        temperatura_min: 8,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'papar, jabuka',
        tijelo_id: '1',
        alkohol_min: 11.5,
        alkohol_max: 13
    },
    {
        id: '38',
        naziv: 'Vermentino',
        tip_id: '2',
        regija: 'Sardinia',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'citrusi, mediteransko bilje',
        tijelo_id: '1',
        alkohol_min: 11.5,
        alkohol_max: 13
    },
    {
        id: '39',
        naziv: 'Assyrtiko',
        tip_id: '2',
        regija: 'Santorini',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'limun, mineralno, slano',
        tijelo_id: '2',
        alkohol_min: 12.5,
        alkohol_max: 13.5
    },
    {
        id: '40',
        naziv: 'Negroamaro',
        tip_id: '1',
        regija: 'Puglia',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'crno voće, začini',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '41',
        naziv: 'Aglianico',
        tip_id: '1',
        regija: 'Campania',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'tamno voće, dim, zemljano',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '42',
        naziv: 'Corvina',
        tip_id: '1',
        regija: 'Veneto',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'trešnja, badem',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '43',
        naziv: 'Lambrusco',
        tip_id: '3',
        regija: 'Emilia-Romagna',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '2',
        arome: 'trešnja, cvjetno',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 12
    },
    {
        id: '44',
        naziv: 'Petit Verdot',
        tip_id: '1',
        regija: 'Bordeaux',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'tamno voće, ljubičica, začini, zemljano',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '45',
        naziv: 'Colombard',
        tip_id: '2',
        regija: 'Gascogne',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'citrusi, zelena jabuka',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 12
    },
    {
        id: '46',
        naziv: 'Pinotage',
        tip_id: '1',
        regija: 'Stellenbosch',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'tamno voće, dim, zemljano',
        tijelo_id: '3',
        alkohol_min: 13,
        alkohol_max: 14.5
    },
    {
        id: '47',
        naziv: 'Graševina',
        tip_id: '2',
        regija: 'Slavonija',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'jabuka, cvjetno, citrus',
        tijelo_id: '2',
        alkohol_min: 11,
        alkohol_max: 12.5
    },
    {
        id: '48',
        naziv: 'Malvazija',
        tip_id: '2',
        regija: 'Istra',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'marelica, cvjetno, badem',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '49',
        naziv: 'Teran',
        tip_id: '1',
        regija: 'Istra',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '1',
        arome: 'višnja, zemljano, svježe',
        tijelo_id: '2',
        alkohol_min: 11.5,
        alkohol_max: 13
    },
    {
        id: '50',
        naziv: 'Plavac Mali',
        tip_id: '1',
        regija: 'Dalmacija',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'sušeno voće, smokva, začini',
        tijelo_id: '3',
        alkohol_min: 14,
        alkohol_max: 16
    },
    {
        id: '51',
        naziv: 'Silvanac Zeleni',
        tip_id: '2',
        regija: 'Franken',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'biljno, jabuka, zemljano',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 12.5
    },
    {
        id: '52',
        naziv: 'Frankovka',
        tip_id: '1',
        regija: 'Burgenland',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '1',
        arome: 'višnja, papar, začini',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '53',
        naziv: 'Rajnski Rizling',
        tip_id: '2',
        regija: 'Rheingau',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '3',
        arome: 'citrusi, petrol, jabuka',
        tijelo_id: '1',
        alkohol_min: 9,
        alkohol_max: 12
    },
    {
        id: '54',
        naziv: 'Vrbnička Žlahtina',
        tip_id: '2',
        regija: 'Krk',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'citrusi, zelena jabuka, blago mineralno',
        tijelo_id: '1',
        alkohol_min: 10,
        alkohol_max: 12
    },
    {
        id: '55',
        naziv: 'Vugava',
        tip_id: '2',
        regija: 'Vis',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '2',
        arome: 'marelica, med, suho voće',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '56',
        naziv: 'Zweigelt',
        tip_id: '1',
        regija: 'Niederosterreich',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '1',
        arome: 'višnja, paprika, začini',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '57',
        naziv: 'Trebbiano',
        tip_id: '2',
        regija: 'Abruzzo',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'limun, jabuka, neutralno',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 12
    },
    {
        id: '58',
        naziv: 'Kadarka',
        tip_id: '1',
        regija: 'Szekszard',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '1',
        arome: 'crveno voće, papar, zemljano',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 12.5
    },
    {
        id: '59',
        naziv: 'Portugizec',
        tip_id: '1',
        regija: 'Štajerska',
        temperatura_min: 12,
        temperatura_max: 14,
        slatkoca_id: '1',
        arome: 'crveno voće, lagano začinsko',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 12
    },
    {
        id: '60',
        naziv: 'Gamay',
        tip_id: '1',
        regija: 'Beaujolais',
        temperatura_min: 12,
        temperatura_max: 14,
        slatkoca_id: '1',
        arome: 'jagoda, višnja, banana',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 13
    },
    {
        id: '61',
        naziv: 'Müller-Thurgau',
        tip_id: '2',
        regija: 'Mosel',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '2',
        arome: 'muškatno, cvjetno, jabuka',
        tijelo_id: '1',
        alkohol_min: 10,
        alkohol_max: 12
    },
    {
        id: '62',
        naziv: 'Debit',
        tip_id: '2',
        regija: 'Dalmacija',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'jabuka, citrus, lagano biljno',
        tijelo_id: '1',
        alkohol_min: 11,
        alkohol_max: 12.5
    },
    {
        id: '63',
        naziv: 'Laški Rizling',
        tip_id: '2',
        regija: 'Štajerska',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '2',
        arome: 'jabuka, cvjetno, blago slatko',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 12
    },
    {
        id: '64',
        naziv: 'Šipon',
        tip_id: '2',
        regija: 'Podravina',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '2',
        arome: 'jabuka, med, mineralno',
        tijelo_id: '2',
        alkohol_min: 11,
        alkohol_max: 13
    },
    {
        id: '65',
        naziv: 'Cinsault',
        tip_id: '1',
        regija: 'Languedoc',
        temperatura_min: 14,
        temperatura_max: 16,
        slatkoca_id: '1',
        arome: 'crveno voće, cvjetno',
        tijelo_id: '1',
        alkohol_min: 11.5,
        alkohol_max: 13
    },
    {
        id: '66',
        naziv: 'Pinot Meunier',
        tip_id: '3',
        regija: 'Champagne',
        temperatura_min: 6,
        temperatura_max: 8,
        slatkoca_id: '1',
        arome: 'crveno voće, cvjetno, lagano kvasasto',
        tijelo_id: '2',
        alkohol_min: 11.5,
        alkohol_max: 12.5
    },
    {
        id: '67',
        naziv: "Nero d'Avola",
        tip_id: '1',
        regija: 'Sicilija',
        temperatura_min: 16,
        temperatura_max: 18,
        slatkoca_id: '1',
        arome: 'tamno voće, šljiva, začini',
        tijelo_id: '3',
        alkohol_min: 13.5,
        alkohol_max: 15
    },
    {
        id: '68',
        naziv: 'Irsai Oliver',
        tip_id: '2',
        regija: 'Mađarska',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '2',
        arome: 'muškatno, cvjetno, grožđe',
        tijelo_id: '1',
        alkohol_min: 10,
        alkohol_max: 11.5
    },
    {
        id: '69',
        naziv: 'Pedro Ximenez',
        tip_id: '4',
        regija: 'Jerez',
        temperatura_min: 10,
        temperatura_max: 14,
        slatkoca_id: '4',
        arome: 'grožđice, smokva, karamela',
        tijelo_id: '3',
        alkohol_min: 15,
        alkohol_max: 18
    },
    {
        id: '70',
        naziv: 'Chablis',
        tip_id: '2',
        regija: 'Burgundy',
        temperatura_min: 10,
        temperatura_max: 12,
        slatkoca_id: '1',
        arome: 'mineralno, limun, jabuka',
        tijelo_id: '2',
        alkohol_min: 12,
        alkohol_max: 13.5
    },
    {
        id: '71',
        naziv: 'Whispering Angel',
        tip_id: '5',
        regija: 'Provence',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '1',
        arome: 'jagoda, citrusi, cvjetno',
        tijelo_id: '1',
        alkohol_min: 12.5,
        alkohol_max: 13.5
    },
    {
        id: '72',
        naziv: 'Rose d’Anjou',
        tip_id: '5',
        regija: 'Loire',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '2',
        arome: 'malina, jagoda',
        tijelo_id: '1',
        alkohol_min: 10.5,
        alkohol_max: 12
    },
    {
        id: '73',
        naziv: 'White Zinfandel',
        tip_id: '5',
        regija: 'California',
        temperatura_min: 8,
        temperatura_max: 10,
        slatkoca_id: '3',
        arome: 'trešnja, lubenica',
        tijelo_id: '1',
        alkohol_min: 9,
        alkohol_max: 11
    },
]

export default {
    vina
}