export const vina = [
    {
        id: 1,
        naziv: 'Cabernet Sauvignon',
        tip: 'crveno',
        regija: 'Bordeaux',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'crno voće, ribiz, šljiva, cedar, duhan',
        tijelo: 'puno',
        alkohol: '13.5-15%'
    },
    {
        id: 2,
        naziv: 'Sangiovese',
        tip: 'crveno',
        regija: 'Toscana',
        jacina: 'srednje-jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'crveno voće, trešnja, začini, zemljano',
        tijelo: 'srednje',
        alkohol: '13-14%'
    },
    {
        id: 3,
        naziv: 'Merlot',
        tip: 'crveno',
        regija: 'Bordeaux',
        jacina: 'srednje',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'šljiva, čokolada, biljno',
        tijelo: 'srednje',
        alkohol: '13-14%'
    },
    {
        id: 4,
        naziv: 'Pinot Noir',
        tip: 'crveno',
        regija: 'Burgundy',
        jacina: 'lagano',
        temperatura: '14-16°C',
        slatkoca: 'suho',
        arome: 'jagoda, trešnja, zemljano',
        tijelo: 'lagano',
        alkohol: '12-13.5%'
    },
    {
        id: 5,
        naziv: 'Syrah',
        tip: 'crveno',
        regija: 'Rhone',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'crno voće, papar, dim',
        tijelo: 'puno',
        alkohol: '13.5-15%'
    },
    {
        id: 6,
        naziv: 'Malbec',
        tip: 'crveno',
        regija: 'Mendoza',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'šljiva, čokolada, dim',
        tijelo: 'puno',
        alkohol: '13.5-15%'
    },
    {
        id: 7,
        naziv: 'Zinfandel',
        tip: 'crveno',
        regija: 'California',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'polusuho',
        arome: 'kupina, papar, džemasto',
        tijelo: 'puno',
        alkohol: '14-16%'
    },
    {
        id: 8,
        naziv: 'Tempranillo',
        tip: 'crveno',
        regija: 'Rioja',
        jacina: 'srednje',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'trešnja, duhan, vanilija',
        tijelo: 'srednje',
        alkohol: '13-14.5%'
    },
    {
        id: 9,
        naziv: 'Grenache',
        tip: 'crveno',
        regija: 'Priorat',
        jacina: 'srednje-jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'malina, začini',
        tijelo: 'srednje',
        alkohol: '13.5-15%'
    },
    {
        id: 10,
        naziv: 'Nebbiolo',
        tip: 'crveno',
        regija: 'Piedmont',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'ruža, katran, trešnja',
        tijelo: 'puno',
        alkohol: '13.5-15%'
    },
    {
        id: 11,
        naziv: 'Barbera',
        tip: 'crveno',
        regija: 'Piedmont',
        jacina: 'srednje',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'trešnja, začini',
        tijelo: 'srednje',
        alkohol: '12.5-14%'
    },
    {
        id: 12,
        naziv: 'Chianti',
        tip: 'crveno',
        regija: 'Toscana',
        jacina: 'srednje',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'trešnja, biljno',
        tijelo: 'srednje',
        alkohol: '12.5-13.5%'
    },
    {
        id: 13,
        naziv: 'Riesling',
        tip: 'bijelo',
        regija: 'Mosel',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'slatko',
        arome: 'citrusi, jabuka, cvjetno',
        tijelo: 'lagano',
        alkohol: '8-12%'
    },
    {
        id: 14,
        naziv: 'Chardonnay',
        tip: 'bijelo',
        regija: 'Burgundy',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'suho',
        arome: 'jabuka, maslac, vanilija',
        tijelo: 'srednje do puno',
        alkohol: '13-14.5%'
    },
    {
        id: 15,
        naziv: 'Sauvignon Blanc',
        tip: 'bijelo',
        regija: 'Loire',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'citrusi, trava',
        tijelo: 'lagano',
        alkohol: '11-13%'
    },
    {
        id: 16,
        naziv: 'Pinot Grigio',
        tip: 'bijelo',
        regija: 'Veneto',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'kruška, limun',
        tijelo: 'lagano',
        alkohol: '11-12.5%'
    },
    {
        id: 17,
        naziv: 'Gewurztraminer',
        tip: 'bijelo',
        regija: 'Alsace',
        jacina: 'srednje',
        temperatura: '8-10°C',
        slatkoca: 'poluslatko',
        arome: 'lišće ruže, liči',
        tijelo: 'srednje',
        alkohol: '13-14%'
    },
    {
        id: 18,
        naziv: 'Viognier',
        tip: 'bijelo',
        regija: 'Rhone',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'suho',
        arome: 'breskva, cvjetno',
        tijelo: 'srednje',
        alkohol: '13-14%'
    },
    {
        id: 19,
        naziv: 'Albarino',
        tip: 'bijelo',
        regija: 'Galicia',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'citrusi, more',
        tijelo: 'lagano',
        alkohol: '11-13%'
    },
    {
        id: 20,
        naziv: 'Moscato',
        tip: 'bijelo',
        regija: 'Piedmont',
        jacina: 'lagano',
        temperatura: '6-8°C',
        slatkoca: 'slatko',
        arome: 'grožđe, cvjetno',
        tijelo: 'lagano',
        alkohol: '5-8%'
    },
    {
        id: 21,
        naziv: 'Prosecco',
        tip: 'pjenušavo',
        regija: 'Veneto',
        jacina: 'lagano',
        temperatura: '6-8°C',
        slatkoca: 'suho',
        arome: 'jabuka, kruška, cvjetno',
        tijelo: 'lagano',
        alkohol: '10.5-11.5%'
    },
    {
        id: 22,
        naziv: 'Champagne',
        tip: 'pjenušavo',
        regija: 'Champagne',
        jacina: 'srednje',
        temperatura: '6-8°C',
        slatkoca: 'suho',
        arome: 'citrusi, tost, kvasac',
        tijelo: 'srednje',
        alkohol: '12-12.5%'
    },
    {
        id: 23,
        naziv: 'Cava',
        tip: 'pjenušavo',
        regija: 'Catalonia',
        jacina: 'srednje',
        temperatura: '6-8°C',
        slatkoca: 'suho',
        arome: 'citrusi, badem',
        tijelo: 'srednje',
        alkohol: '11.5-12.5%'
    },
    {
        id: 24,
        naziv: 'Shiraz',
        tip: 'crveno',
        regija: 'Barossa Valley',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'kupina, papar, čokolada',
        tijelo: 'puno',
        alkohol: '14-15.5%'
    },
    {
        id: 25,
        naziv: 'Petite Sirah',
        tip: 'crveno',
        regija: 'California',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'borovnica, papar, tamno voće',
        tijelo: 'puno',
        alkohol: '13.5-15%'
    },
    {
        id: 26,
        naziv: 'Carmenere',
        tip: 'crveno',
        regija: 'Central Valley',
        jacina: 'srednje-jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'paprika, šljiva, začini',
        tijelo: 'srednje',
        alkohol: '13-14.5%'
    },
    {
        id: 27,
        naziv: 'Primitivo',
        tip: 'crveno',
        regija: 'Puglia',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'polusuho',
        arome: 'šljiva, džem, začini',
        tijelo: 'puno',
        alkohol: '14-16%'
    },
    {
        id: 28,
        naziv: 'Montepulciano',
        tip: 'crveno',
        regija: 'Abruzzo',
        jacina: 'srednje',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'trešnja, začini',
        tijelo: 'srednje',
        alkohol: '12.5-14%'
    },
    {
        id: 29,
        naziv: 'Soave',
        tip: 'bijelo',
        regija: 'Veneto',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'jabuka, cvjetno',
        tijelo: 'lagano',
        alkohol: '11-12.5%'
    },
    {
        id: 30,
        naziv: 'Greco di Tufo',
        tip: 'bijelo',
        regija: 'Campania',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'suho',
        arome: 'kruška, mineralno',
        tijelo: 'srednje',
        alkohol: '12-13.5%'
    },
    {
        id: 31,
        naziv: 'Chenin Blanc',
        tip: 'bijelo',
        regija: 'Loire',
        jacina: 'srednje',
        temperatura: '8-10°C',
        slatkoca: 'poluslatko',
        arome: 'jabuka, med, cvjetno',
        tijelo: 'srednje',
        alkohol: '11-13.5%'
    },
    {
        id: 32,
        naziv: 'Semillon',
        tip: 'bijelo',
        regija: 'Bordeaux',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'suho',
        arome: 'limun, vosak, med',
        tijelo: 'srednje',
        alkohol: '11.5-13.5%'
    },
    {
        id: 33,
        naziv: 'Tokaji',
        tip: 'bijelo',
        regija: 'Tokaj',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'slatko',
        arome: 'med, marelica, cvjetno',
        tijelo: 'puno',
        alkohol: '11-13%'
    },
    {
        id: 34,
        naziv: 'Porto',
        tip: 'fortificirano',
        regija: 'Douro',
        jacina: 'jako',
        temperatura: '12-16°C',
        slatkoca: 'slatko',
        arome: 'sušeno voće, čokolada',
        tijelo: 'puno',
        alkohol: '19-22%'
    },
    {
        id: 35,
        naziv: 'Sherry',
        tip: 'fortificirano',
        regija: 'Jerez',
        jacina: 'srednje-jako',
        temperatura: '8-14°C',
        slatkoca: 'suho',
        arome: 'orah, sol, oksidativno',
        tijelo: 'srednje',
        alkohol: '15-20%'
    },
    {
        id: 36,
        naziv: 'Madeira',
        tip: 'fortificirano',
        regija: 'Madeira',
        jacina: 'jako',
        temperatura: '14-16°C',
        slatkoca: 'slatko',
        arome: 'karamela, orašasto',
        tijelo: 'puno',
        alkohol: '17-20%'
    },
    {
        id: 37,
        naziv: 'Gruner Veltliner',
        tip: 'bijelo',
        regija: 'Wachau',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'papar, jabuka',
        tijelo: 'lagano',
        alkohol: '11.5-13%'
    },
    {
        id: 38,
        naziv: 'Vermentino',
        tip: 'bijelo',
        regija: 'Sardinia',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'citrusi, mediteransko bilje',
        tijelo: 'lagano',
        alkohol: '11.5-13%'
    },
    {
        id: 39,
        naziv: 'Assyrtiko',
        tip: 'bijelo',
        regija: 'Santorini',
        jacina: 'srednje',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'limun, mineralno, slano',
        tijelo: 'srednje',
        alkohol: '12.5-13.5%'
    },
    {
        id: 40,
        naziv: 'Negroamaro',
        tip: 'crveno',
        regija: 'Puglia',
        jacina: 'srednje-jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'crno voće, začini',
        tijelo: 'srednje do puno',
        alkohol: '13.5-15%'
    },
    {
        id: 41,
        naziv: 'Aglianico',
        tip: 'crveno',
        regija: 'Campania',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'tamno voće, dim, zemljano',
        tijelo: 'puno',
        alkohol: '13.5-15%'
    },
    {
        id: 42,
        naziv: 'Corvina',
        tip: 'crveno',
        regija: 'Veneto',
        jacina: 'srednje',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'trešnja, badem',
        tijelo: 'srednje',
        alkohol: '12-13.5%'
    },
    {
        id: 43,
        naziv: 'Lambrusco',
        tip: 'pjenušavo',
        regija: 'Emilia-Romagna',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'polusuho',
        arome: 'trešnja, cvjetno',
        tijelo: 'lagano',
        alkohol: '10.5-12%'
    },
    {
        id: 44,
        naziv: 'Petit Verdot',
        tip: 'crveno',
        regija: 'Bordeaux',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'tamno voće, ljubičica, začini, zemljano',
        tijelo: 'puno',
        alkohol: '13.5-15%',
        tanini: 'vrlo visoki'
    },
    {
        id: 45,
        naziv: 'Colombard',
        tip: 'bijelo',
        regija: 'Gascogne',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'citrusi, zelena jabuka',
        tijelo: 'lagano',
        alkohol: '10.5-12%'
    },
    {
        id: 46,
        naziv: 'Pinotage',
        tip: 'crveno',
        regija: 'Stellenbosch',
        jacina: 'srednje-jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'tamno voće, dim, zemljano',
        tijelo: 'srednje do puno',
        alkohol: '13-14.5%'
    },
    {
        id: 47,
        naziv: 'Graševina',
        tip: 'bijelo',
        regija: 'Slavonija',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'jabuka, cvjetno, citrus',
        tijelo: 'lagano do srednje',
        alkohol: '11-12.5%'
    },
    {
        id: 48,
        naziv: 'Malvazija',
        tip: 'bijelo',
        regija: 'Istra',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'suho',
        arome: 'marelica, cvjetno, badem',
        tijelo: 'srednje',
        alkohol: '12-13.5%'
    },
    {
        id: 49,
        naziv: 'Teran',
        tip: 'crveno',
        regija: 'Istra',
        jacina: 'srednje',
        temperatura: '14-16°C',
        slatkoca: 'suho',
        arome: 'višnja, zemljano, svježe',
        tijelo: 'srednje',
        alkohol: '11.5-13%'
    },
    {
        id: 50,
        naziv: 'Plavac Mali',
        tip: 'crveno',
        regija: 'Dalmacija',
        jacina: 'jako',
        temperatura: '16-18°C',
        slatkoca: 'suho',
        arome: 'sušeno voće, smokva, začini',
        tijelo: 'puno',
        alkohol: '14-16%'
    },
    {
        id: 51,
        naziv: 'Silvanac Zeleni',
        tip: 'bijelo',
        regija: 'Franken',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'biljno, jabuka, zemljano',
        tijelo: 'lagano',
        alkohol: '11-12.5%'
    },
    {
        id: 52,
        naziv: 'Frankovka',
        tip: 'crveno',
        regija: 'Burgenland',
        jacina: 'srednje',
        temperatura: '14-16°C',
        slatkoca: 'suho',
        arome: 'višnja, papar, začini',
        tijelo: 'srednje',
        alkohol: '12-13.5%'
    },
    {
        id: 53,
        naziv: 'Rajnski Rizling',
        tip: 'bijelo',
        regija: 'Rheingau',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'poluslatko',
        arome: 'citrusi, petrol, jabuka',
        tijelo: 'lagano',
        alkohol: '9-12%'
    },
    {
        id: 54,
        naziv: 'Vrbnička Žlahtina',
        tip: 'bijelo',
        regija: 'Kvarner (otok Krk)',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'citrusi, zelena jabuka, blago mineralno',
        tijelo: 'lagano',
        alkohol: '10-12%'
    },
    {
        id: 55,
        naziv: 'Vugava',
        tip: 'bijelo',
        regija: 'Dalmacija (otok Vis)',
        jacina: 'srednje',
        temperatura: '10-12°C',
        slatkoca: 'polusuho',
        arome: 'marelica, med, suho voće',
        tijelo: 'srednje',
        alkohol: '12-13.5%'
    },
    {
        id: 56,
        naziv: 'Zweigelt',
        tip: 'crveno',
        regija: 'Niederosterreich',
        jacina: 'srednje',
        temperatura: '14-16°C',
        slatkoca: 'suho',
        arome: 'višnja, paprika, začini',
        tijelo: 'srednje',
        alkohol: '12-13.5%'
    },
    {
        id: 57,
        naziv: 'Trebbiano',
        tip: 'bijelo',
        regija: 'Abruzzo',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'suho',
        arome: 'limun, jabuka, neutralno',
        tijelo: 'lagano',
        alkohol: '10.5-12%'
    },
    {
        id: 58,
        naziv: 'Kadarka',
        tip: 'crveno',
        regija: 'Szekszard',
        jacina: 'lagano',
        temperatura: '14-16°C',
        slatkoca: 'suho',
        arome: 'crveno voće, papar, zemljano',
        tijelo: 'lagano',
        alkohol: '11-12.5%'
    },
    {
        id: 59,
        naziv: 'Portugizec',
        tip: 'crveno',
        regija: 'Štajerska',
        jacina: 'lagano',
        temperatura: '12-14°C',
        slatkoca: 'suho',
        arome: 'crveno voće, lagano začinsko',
        tijelo: 'lagano',
        alkohol: '10.5-12%'
    },
    {
        id: 60,
        naziv: 'Gamay',
        tip: 'crveno',
        regija: 'Beaujolais',
        jacina: 'lagano',
        temperatura: '12-14°C',
        slatkoca: 'suho',
        arome: 'jagoda, višnja, banana',
        tijelo: 'lagano',
        alkohol: '11-13%'
    },
    {
        id: 61,
        naziv: 'Müller-Thurgau',
        tip: 'bijelo',
        regija: 'Mosel',
        jacina: 'lagano',
        temperatura: '8-10°C',
        slatkoca: 'polusuho',
        arome: 'muškatno, cvjetno, jabuka',
        tijelo: 'lagano',
        alkohol: '10-12%'
    }
];
