export const sirevi = [
    {
        id: '1',
        naziv: 'Cheddar',
        tip_id: '5',
        vrsta_id: '1',
        zrenje_id: '3',
        regija: 'Somerset',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'orašast, pun, blago pikantan'
    },
    {
        id: '2',
        naziv: 'Brie',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Île-de-France',
        intenzitet_id: '1',
        masnoca_id: '3',
        okus: 'maslac, blago gljivasto'
    },
    {
        id: '3',
        naziv: 'Camembert',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Normandija',
        intenzitet_id: '2',
        masnoca_id: '3',
        okus: 'zemljano, gljivasto'
    },
    {
        id: '4',
        naziv: 'Gouda',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Južna Nizozemska',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'karamel, orašasto'
    },
    {
        id: '5',
        naziv: 'Edam',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Sjeverna Nizozemska',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'blago orašasto'
    },
    {
        id: '6',
        naziv: 'Parmezan',
        tip_id: '5',
        vrsta_id: '1',
        zrenje_id: '3',
        regija: 'Emilia-Romagna',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'slano, orašasto, umami'
    },
    {
        id: '7',
        naziv: 'Grana Padano',
        tip_id: '3',
        vrsta_id: '1',
        zrenje_id: '3',
        regija: 'Padanska nizina',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'orašasto, blago slano'
    },
    {
        id: '8',
        naziv: 'Roquefort',
        tip_id: '4',
        vrsta_id: '2',
        zrenje_id: '2',
        regija: 'Aveyron',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'slano, pikantno'
    },
    {
        id: '9',
        naziv: 'Gorgonzola',
        tip_id: '4',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Lombardija',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'pikantno, slatko'
    },
    {
        id: '10',
        naziv: 'Stilton',
        tip_id: '4',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Midlands',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'bogato, pikantno'
    },
    {
        id: '11',
        naziv: 'Feta',
        tip_id: '1',
        vrsta_id: '2',
        zrenje_id: '1',
        regija: 'Makedonija',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'slano, kiselo'
    },
    {
        id: '12',
        naziv: 'Mozzarella',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Campania',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'mliječno, blago'
    },
    {
        id: '13',
        naziv: 'Ricotta',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Toscana',
        intenzitet_id: '1',
        masnoca_id: '1',
        okus: 'blago slatko'
    },
    {
        id: '14',
        naziv: 'Mascarpone',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Lombardija',
        intenzitet_id: '1',
        masnoca_id: '3',
        okus: 'slatko, bogato'
    },
    {
        id: '15',
        naziv: 'Emmental',
        tip_id: '3',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Emmental',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'orašasto'
    },
    {
        id: '16',
        naziv: 'Gruyere',
        tip_id: '5',
        vrsta_id: '1',
        zrenje_id: '3',
        regija: 'Gruyères',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'orašasto, slatko'
    },
    {
        id: '17',
        naziv: 'Comte',
        tip_id: '5',
        vrsta_id: '1',
        zrenje_id: '3',
        regija: 'Jura',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'orašasto, voćno'
    },
    {
        id: '18',
        naziv: 'Reblochon',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Savoja',
        intenzitet_id: '2',
        masnoca_id: '3',
        okus: 'maslac, orašasto'
    },
    {
        id: '19',
        naziv: 'Taleggio',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Lombardija',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'jak, aromatičan'
    },
    {
        id: '20',
        naziv: 'Pecorino',
        tip_id: '5',
        vrsta_id: '2',
        zrenje_id: '3',
        regija: 'Sardinija',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'slan, pikantan'
    },
    {
        id: '21',
        naziv: 'Manchego',
        tip_id: '3',
        vrsta_id: '2',
        zrenje_id: '2',
        regija: 'La Mancha',
        intenzitet_id: '2',
        masnoca_id: '3',
        okus: 'orašasto, blago slano'
    },
    {
        id: '22',
        naziv: 'Halloumi',
        tip_id: '2',
        vrsta_id: '4',
        zrenje_id: '1',
        regija: 'Cipar',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'slano'
    },
    {
        id: '23',
        naziv: 'Paški sir',
        tip_id: '5',
        vrsta_id: '2',
        zrenje_id: '3',
        regija: 'Pag',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'slan, aromatičan'
    },
    {
        id: '24',
        naziv: 'Trappista',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Panonska nizina',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'blago, mliječno'
    },
    {
        id: '25',
        naziv: 'Kashkaval',
        tip_id: '2',
        vrsta_id: '2',
        zrenje_id: '2',
        regija: 'Balkan',
        intenzitet_id: '2',
        masnoca_id: '3',
        okus: 'blago pikantan'
    },
    {
        id: '26',
        naziv: 'Tilsit',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Istočna Pruska',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'blago pikantan'
    },
    {
        id: '27',
        naziv: 'Lički škripavac',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Lika',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'mliječno, blago slano'
    },
    {
        id: '28',
        naziv: 'Prgica',
        tip_id: '3',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Međimurje',
        intenzitet_id: '3',
        masnoca_id: '1',
        okus: 'pikantno, paprika'
    },
    {
        id: '29',
        naziv: 'Krčki sir',
        tip_id: '3',
        vrsta_id: '2',
        zrenje_id: '2',
        regija: 'Krk',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'aromatično, biljno'
    },
    {
        id: '30',
        naziv: 'Dubrovački sir',
        tip_id: '3',
        vrsta_id: '4',
        zrenje_id: '2',
        regija: 'Dubrovnik',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'bogato, aromatično'
    },
    {
        id: '31',
        naziv: 'Sir iz mišine',
        tip_id: '5',
        vrsta_id: '2',
        zrenje_id: '3',
        regija: 'Dalmacija',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'intenzivno, pikantno'
    },
    {
        id: '32',
        naziv: 'Wensleydale',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Yorkshire',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'svježe, blago kiselo'
    },
    {
        id: '33',
        naziv: 'Dimsi',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Zagorje',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'dimljeno, blago pikantno'
    },
    {
        id: '34',
        naziv: 'Caprilo',
        tip_id: '1',
        vrsta_id: '3',
        zrenje_id: '1',
        regija: 'Zagorje',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'svježe, blago kiselo'
    },
    {
        id: '35',
        naziv: 'Chèvre',
        tip_id: '1',
        vrsta_id: '3',
        zrenje_id: '1',
        regija: 'Loire',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'svježe, blago kiselo'
    },
    {
        id: '36',
        naziv: 'Bûcheron',
        tip_id: '2',
        vrsta_id: '3',
        zrenje_id: '2',
        regija: 'Loire',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'kremasto, blago orašasto'
    },
    {
        id: '37',
        naziv: 'Garrotxa',
        tip_id: '2',
        vrsta_id: '3',
        zrenje_id: '2',
        regija: 'Katalonija',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'zemljano, orašasto'
    },
    {
        id: '38',
        naziv: 'Caprino',
        tip_id: '1',
        vrsta_id: '3',
        zrenje_id: '1',
        regija: 'Pijemont',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'svježe, blago kiselo'
    },
    {
        id: '39',
        naziv: 'Asiago',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Veneto',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'orašasto, blago slatko'
    },
    {
        id: '40',
        naziv: 'Provolone',
        tip_id: '5',
        vrsta_id: '1',
        zrenje_id: '3',
        regija: 'Južna Italija',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'pikantno, dimljeno'
    },
    {
        id: '41',
        naziv: 'Scamorza',
        tip_id: '2',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Apulija',
        intenzitet_id: '1',
        masnoca_id: '2',
        okus: 'mliječno, blago dimljeno'
    },
    {
        id: '42',
        naziv: 'Saint-Nectaire',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '2',
        regija: 'Auvergne',
        intenzitet_id: '2',
        masnoca_id: '3',
        okus: 'orašasto, zemljano'
    },
    {
        id: '43',
        naziv: 'Langres',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Champagne',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'intenzivno, kremasto'
    },
    {
        id: '44',
        naziv: 'Valençay',
        tip_id: '1',
        vrsta_id: '3',
        zrenje_id: '1',
        regija: 'Loire',
        intenzitet_id: '2',
        masnoca_id: '2',
        okus: 'svježe, blago orašasto'
    },
    {
        id: '45',
        naziv: 'Idiazabal',
        tip_id: '5',
        vrsta_id: '2',
        zrenje_id: '2',
        regija: 'Baskija',
        intenzitet_id: '3',
        masnoca_id: '3',
        okus: 'dimljeno, orašasto'
    },
    {
        id: '46',
        naziv: 'Burrata',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Apulija',
        intenzitet_id: '1',
        masnoca_id: '3',
        okus: 'kremasto, mliječno, bogato'
    },
    {
        id: '47',
        naziv: 'Stracciatella',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Apulija',
        intenzitet_id: '1',
        masnoca_id: '3',
        okus: 'vrlo kremasto, svježe, mliječno'
    },
    {
        id: '48',
        naziv: 'Cottage cheese',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Srednja Europa',
        intenzitet_id: '1',
        masnoca_id: '1',
        okus: 'svježe, blago kiselo'
    },
    {
        id: '49',
        naziv: 'Quark',
        tip_id: '1',
        vrsta_id: '1',
        zrenje_id: '1',
        regija: 'Srednja Europa',
        intenzitet_id: '1',
        masnoca_id: '1',
        okus: 'blago kiselo, svježe'
    },
    {
        id: '50',
        naziv: 'Skuta',
        tip_id: '1',
        vrsta_id: '4',
        zrenje_id: '1',
        regija: 'Alpe',
        intenzitet_id: '1',
        masnoca_id: '1',
        okus: 'lagano, mliječno, blago'
    }
]

export default {
    sirevi
}