export const sirevi = [
    {
        id: 1,
        naziv: 'Cheddar',
        tip: 'tvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje do dugo',
        regija: 'Somerset',
        intezitet: 'srednji do jak',
        masnoce: 'visoke',
        okus: 'orašast, pun, blago pikantan'
    },
    {
        id: 2,
        naziv: 'Brie',
        tip: 'mekani',
        vrsta: 'kravlji',
        zrenje: 'kratko',
        regija: 'Île-de-France',
        intezitet: 'blag',
        masnoce: 'visoke',
        okus: 'maslac, blago gljivasto'
    },
    {
        id: 3,
        naziv: 'Camembert',
        tip: 'mekani',
        vrsta: 'kravlji',
        zrenje: 'kratko',
        regija: 'Normandija',
        intezitet: 'srednji',
        masnoce: 'visoke',
        okus: 'zemljano, gljivasto'
    },
    {
        id: 4,
        naziv: 'Gouda',
        tip: 'polutvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Gouda',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'karamel, orašasto'
    },
    {
        id: 5,
        naziv: 'Edam',
        tip: 'polutvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Edam',
        intezitet: 'blag',
        masnoce: 'srednje',
        okus: 'blago orašasto'
    },
    {
        id: 6,
        naziv: 'Parmezan',
        tip: 'tvrdi',
        vrsta: 'kravlji',
        zrenje: 'dugo',
        regija: 'Parma',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'slano, orašasto, umami'
    },
    {
        id: 7,
        naziv: 'Grana Padano',
        tip: 'tvrdi',
        vrsta: 'kravlji',
        zrenje: 'dugo',
        regija: 'Padana nizina',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'orašasto, blago slano'
    },
    {
        id: 8,
        naziv: 'Roquefort',
        tip: 'plavi',
        vrsta: 'ovčji',
        zrenje: 'srednje',
        regija: 'Roquefort',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'slano, pikantno'
    },
    {
        id: 9,
        naziv: 'Gorgonzola',
        tip: 'plavi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Lombardija',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'pikantno, slatko'
    },
    {
        id: 10,
        naziv: 'Stilton',
        tip: 'plavi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Nottinghamshire',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'bogato, pikantno'
    },
    {
        id: 11,
        naziv: 'Feta',
        tip: 'mekani',
        vrsta: 'ovčji',
        zrenje: 'kratko',
        regija: 'Makedonija',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'slano, kiselo'
    },
    {
        id: 12,
        naziv: 'Mozzarella',
        tip: 'svježi',
        vrsta: 'kravlji',
        zrenje: 'svježi',
        regija: 'Campania',
        intezitet: 'blag',
        masnoce: 'srednje',
        okus: 'mliječno, blago'
    },
    {
        id: 13,
        naziv: 'Ricotta',
        tip: 'svježi',
        vrsta: 'kravlji',
        zrenje: 'svježi',
        regija: 'Toscana',
        intezitet: 'blag',
        masnoce: 'niske',
        okus: 'blago slatko'
    },
    {
        id: 14,
        naziv: 'Mascarpone',
        tip: 'svježi',
        vrsta: 'kravlji',
        zrenje: 'svježi',
        regija: 'Lombardija',
        intezitet: 'blag',
        masnoce: 'visoke',
        okus: 'slatko, bogato'
    },
    {
        id: 15,
        naziv: 'Emmental',
        tip: 'tvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Emmental',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'orašasto'
    },
    {
        id: 16,
        naziv: 'Gruyere',
        tip: 'tvrdi',
        vrsta: 'kravlji',
        zrenje: 'dugo',
        regija: 'Gruyères',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'orašasto, slatko'
    },
    {
        id: 17,
        naziv: 'Comte',
        tip: 'tvrdi',
        vrsta: 'kravlji',
        zrenje: 'dugo',
        regija: 'Jura',
        intezitet: 'srednje-jak',
        masnoce: 'visoke',
        okus: 'orašasto, voćno'
    },
    {
        id: 18,
        naziv: 'Reblochon',
        tip: 'mekani',
        vrsta: 'kravlji',
        zrenje: 'kratko',
        regija: 'Savoja',
        intezitet: 'srednji',
        masnoce: 'visoke',
        okus: 'maslac, orašasto'
    },
    {
        id: 19,
        naziv: 'Taleggio',
        tip: 'mekani',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Lombardija',
        intezitet: 'srednje-jak',
        masnoce: 'visoke',
        okus: 'jak, aromatičan'
    },
    {
        id: 20,
        naziv: 'Pecorino',
        tip: 'tvrdi',
        vrsta: 'ovčji',
        zrenje: 'dugo',
        regija: 'Sardinija',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'slan, pikantan'
    },
    {
        id: 21,
        naziv: 'Manchego',
        tip: 'tvrdi',
        vrsta: 'ovčji',
        zrenje: 'srednje',
        regija: 'La Mancha',
        intezitet: 'srednji',
        masnoce: 'visoke',
        okus: 'orašasto, blago slano'
    },
    {
        id: 22,
        naziv: 'Halloumi',
        tip: 'polutvrdi',
        vrsta: 'miješano',
        zrenje: 'kratko',
        regija: 'Nicosia',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'slano'
    },
    {
        id: 23,
        naziv: 'Paški sir',
        tip: 'tvrdi',
        vrsta: 'ovčji',
        zrenje: 'dugo',
        regija: 'Pag',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'slan, aromatičan'
    },
    {
        id: 24,
        naziv: 'Trappista',
        tip: 'polutvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Alföld',
        intezitet: 'blag',
        masnoce: 'srednje',
        okus: 'blago, mliječno'
    },
    {
        id: 25,
        naziv: 'Kashkaval',
        tip: 'polutvrdi',
        vrsta: 'ovčji',
        zrenje: 'srednje',
        regija: 'Balkan',
        intezitet: 'srednji',
        masnoce: 'visoke',
        okus: 'blago pikantan'
    },
    {
        id: 26,
        naziv: 'Tilsit',
        tip: 'polutvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Schleswig-Holstein',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'blago pikantan'
    },
    {
        id: 27,
        naziv: 'Lički škripavac',
        tip: 'svježi',
        vrsta: 'kravlji',
        zrenje: 'svježi',
        regija: 'Lika',
        intezitet: 'blag',
        masnoce: 'srednje',
        okus: 'mliječno, blago slano'
    },
    {
        id: 28,
        naziv: 'Prgica',
        tip: 'svježi',
        vrsta: 'kravlji',
        zrenje: 'kratko',
        regija: 'Međimurje',
        intezitet: 'jak',
        masnoce: 'niske',
        okus: 'pikantno, paprika'
    },
    {
        id: 29,
        naziv: 'Krčki sir',
        tip: 'tvrdi',
        vrsta: 'ovčji',
        zrenje: 'srednje',
        regija: 'Krk',
        intezitet: 'srednje-jak',
        masnoce: 'visoke',
        okus: 'aromatično, biljno'
    },
    {
        id: 30,
        naziv: 'Dubrovački sir',
        tip: 'tvrdi',
        vrsta: 'miješano',
        zrenje: 'srednje',
        regija: 'Dubrovnik',
        intezitet: 'srednje-jak',
        masnoce: 'visoke',
        okus: 'bogato, aromatično'
    },
    {
        id: 31,
        naziv: 'Sir iz mišine',
        tip: 'tvrdi',
        vrsta: 'ovčji',
        zrenje: 'dugo',
        regija: 'Dalmacija',
        intezitet: 'jak',
        masnoce: 'visoke',
        okus: 'intenzivno, pikantno'
    },
    {
        id: 32,
        naziv: 'Wensleydale',
        tip: 'polutvrdi',
        vrsta: 'kravlji',
        zrenje: 'kratko do srednje',
        regija: 'Yorkshire',
        intezitet: 'blag',
        masnoce: 'srednje',
        okus: 'svježe, blago kiselo'
    },
    {
        id: 33,
        naziv: 'Dimsi',
        tip: 'polutvrdi',
        vrsta: 'kravlji',
        zrenje: 'srednje',
        regija: 'Hrvatska',
        intezitet: 'srednji',
        masnoce: 'visoke',
        okus: 'dimljeno, blago pikantno'
    },
    {
        id: 34,
        naziv: 'Caprilo',
        tip: 'mekani',
        vrsta: 'kozji',
        zrenje: 'kratko',
        regija: 'Hrvatska',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'svježe, blago kiselo'
    },
    {
        id: 35,
        naziv: 'Chèvre',
        tip: 'mekani',
        vrsta: 'kozji',
        zrenje: 'kratko',
        regija: 'Loire',
        intezitet: 'blagi',
        masnoce: 'srednje',
        okus: 'svježe, blago kiselo'
    },
    {
        id: 36,
        naziv: 'Bûcheron',
        tip: 'polumekani',
        vrsta: 'kozji',
        zrenje: 'srednje',
        regija: 'Loire',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'kremasto, blago orašasto'
    },
    {
        id: 37,
        naziv: 'Garrotxa',
        tip: 'polutvrdi',
        vrsta: 'kozji',
        zrenje: 'srednje',
        regija: 'Katalonija',
        intezitet: 'srednji',
        masnoce: 'srednje',
        okus: 'zemljano, orašasto'
    },
    {
        id: 38,
        naziv: 'Caprino',
        tip: 'mekani',
        vrsta: 'kozji',
        zrenje: 'kratko',
        regija: 'Pijemont',
        intezitet: 'blagi',
        masnoce: 'srednje',
        okus: 'svježe, blago kiselo'
    }
]