export const pairingRules = {
  "Cabernet Sauvignon": ["Cheddar", "Gouda", "Parmezan", "Paški sir"],
  "Merlot": ["Gouda", "Edam", "Cheddar"],
  "Pinot Noir": ["Brie", "Camembert", "Reblochon"],
  "Syrah": ["Gorgonzola", "Roquefort", "Cheddar"],
  "Malbec": ["Cheddar", "Gouda", "Parmezan"],
  "Zinfandel": ["Gouda", "Edam", "Cheddar"],
  "Tempranillo": ["Manchego", "Cheddar"],
  "Nebbiolo": ["Parmezan", "Grana Padano"],
  "Barbera": ["Mozzarella", "Ricotta"],
  "Chianti": ["Parmezan", "Pecorino"],
  "Grenache": ["Gouda", "Edam"],
  "Montepulciano": ["Pecorino", "Parmezan"],
  "Sangiovese": ["Pecorino", "Parmezan"],
  "Primitivo": ["Gorgonzola", "Cheddar"],
  "Plavac Mali": ["Paški sir", "Sir iz mišine"],
  "Teran": ["Trappista", "Gouda"],
  "Frankovka": ["Edam", "Gouda"],
  "Zweigelt": ["Trappista", "Edam"],
  "Gamay": ["Brie", "Camembert"],
  "Kadarka": ["Brie", "Mozzarella"],
  "Chardonnay": ["Brie", "Camembert", "Gruyere"],
  "Sauvignon Blanc": ["Feta", "Caprilo"],
  "Riesling": ["Roquefort", "Gorgonzola"],
  "Pinot Grigio": ["Mozzarella", "Ricotta"],
  "Gewurztraminer": ["Munster", "Taleggio", "Gorgonzola"],
  "Viognier": ["Brie", "Camembert"],
  "Albarino": ["Mozzarella", "Feta"],
  "Moscato": ["Gorgonzola", "Roquefort"],
  "Soave": ["Ricotta", "Mozzarella"],
  "Greco di Tufo": ["Mozzarella", "Burrata"],
  "Chenin Blanc": ["Brie", "Camembert"],
  "Semillon": ["Brie", "Gruyere"],
  "Tokaji": ["Roquefort", "Gorgonzola"],
  "Gruner Veltliner": ["Feta", "Caprilo"],
  "Vermentino": ["Mozzarella", "Feta"],
  "Assyrtiko": ["Feta"],
  "Graševina": ["Svježi sir", "Mozzarella"],
  "Malvazija": ["Brie", "Caprilo"],
  "Vrbnička Žlahtina": ["Mozzarella", "Ricotta"],
  "Vugava": ["Gorgonzola", "Taleggio"],
  "Trebbiano": ["Ricotta", "Mozzarella"],
  "Müller-Thurgau": ["Brie", "Camembert"],
  "Prosecco": ["Parmezan", "Grana Padano", "Mozzarella"],
  "Champagne": ["Brie", "Camembert", "Parmezan"],
  "Cava": ["Manchego", "Cheddar"],
  "Porto": ["Stilton", "Gorgonzola"],
  "Sherry": ["Manchego", "Comte"],
  "Madeira": ["Parmezan", "Gruyere"]
};


